# Business Problem Understanding:
* Bankruptcy prediction is an important for modern economies because early
warnings of bankrupt help not only the investor but also public policy makers to
take proactive steps to minimize the impact of bankruptcies.

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import warnings
warnings.filterwarnings("ignore")
import matplotlib.pyplot as plt

In [2]:
df1 = pd.read_csv('/Users/vaibhavkadam/Downloads/polish companies bankruptcy data/1year.csv')
df2 = pd.read_csv("/Users/vaibhavkadam/Downloads/polish companies bankruptcy data/2year.csv")
df3 = pd.read_csv("/Users/vaibhavkadam/Downloads/polish companies bankruptcy data/3year.csv")
df4 = pd.read_csv("/Users/vaibhavkadam/Downloads/polish companies bankruptcy data/4year.csv")
df5 = pd.read_csv("/Users/vaibhavkadam/Downloads/polish companies bankruptcy data/5year.csv")

In [3]:
df6 = pd.concat((df1,df2,df3,df4,df5), axis=0)

In [4]:
df6

Attr1    Attr2     Attr3    Attr4     Attr5    Attr6     Attr7  \
0     0.200550  0.37951  0.396410  2.04720   32.3510  0.38825  0.249760   
1     0.209120  0.49988  0.472250  1.94470   14.7860  0.00000  0.258340   
2     0.248660  0.69592  0.267130  1.55480   -1.1523  0.00000  0.309060   
3     0.081483  0.30734  0.458790  2.49280   51.9520  0.14988  0.092704   
4     0.187320  0.61323  0.229600  1.40630   -7.3128  0.18732  0.187320   
...        ...      ...       ...      ...       ...      ...       ...   
5905  0.012898  0.70621  0.038857  1.17220  -18.9070  0.00000  0.013981   
5906 -0.578050  0.96702 -0.800850  0.16576  -67.3650 -0.57805 -0.578050   
5907 -0.179050  1.25530 -0.275990  0.74554 -120.4400 -0.17905 -0.154930   
5908 -0.108860  0.74394  0.015449  1.08780  -17.0030 -0.10886 -0.109180   
5909 -0.105370  0.53629 -0.045578  0.91478  -56.0680 -0.10537 -0.109940   

        Attr8    Attr9    Attr10  ...    Attr56    Attr57   Attr58    Attr59  \
0     1.33050  1.13890  0.504940  ...  0.121960  0.397180  0.87804  0.001924   
1     0.99601  1.69960  0.497880  ...  0.121300  0.420020  0.85300  0.000000   
2     0.43695  1.30900  0.304080  ...  0.241140  0.817740  0.76599  0.694840   
3     1.86610  1.05710  0.573530  ...  0.054015  0.142070  0.94598  0.000000   
4     0.63070  1.15590  0.386770  ...  0.134850  0.484310  0.86515  0.124440   
...       ...      ...       ...  ...       ...       ...      ...       ...   
5905  0.41600  1.67680  0.293790  ...  0.020169  0.043904  1.01220  1.259400   
5906 -0.40334  0.93979 -0.390040  ... -0.064073  1.482000  1.06410 -0.018084   
5907 -0.26018  1.17490 -0.326590  ...  0.148880  0.548240  0.85112 -0.522430   
5908  0.12531  0.84516  0.093224  ... -0.183200 -1.167700  1.18320  6.092400   
5909  0.86460  0.95040  0.463670  ... -0.052186 -0.227250  1.05220  0.003196   

        Attr60   Attr61   Attr62  Attr63    Attr64  class  
0       8.4160   5.1372   82.658  4.4158   7.42770      0  
1       4.1486   3.2732  107.350  3.4000  60.98700      0  
2       4.9909   3.9510  134.270  2.7185   5.20780      0  
3       4.5746   3.6147   86.435  4.2228   5.54970      0  
4       6.3985   4.3158  127.210  2.8692   7.89800      0  
...        ...      ...      ...     ...       ...    ...  
5905   13.4720  12.4320   49.117  7.4313   2.27990      1  
5906  110.7200  44.7590   81.220  4.4940   5.13050      1  
5907    9.8526   3.4892  207.870  1.7559   9.95270      1  
5908   13.8860   6.0769   83.122  4.3911   0.95575      1  
5909    7.7332   4.7174  136.850  2.6672   2.79270      1  

[43405 rows x 65 columns]

In [5]:
# Dictionary mapping old column names to new column names
column_name_mapping = {
    'Attr1': 'Net_Profit_to_Total_Assets',
    'Attr2': 'Total_Liabilities_to_Total_Assets',
    'Attr3': 'Working_Capital_to_Total_Assets',
    'Attr4': 'Current_Assets_to_Short_Term_Liabilities',
    'Attr5': 'Liquidity_Ratio',
    'Attr6': 'Retained_Earnings_to_Total_Assets',
    'Attr7': 'EBIT_to_Total_Assets',
    'Attr8': 'Book_Value_of_Equity_to_Total_Liabilities',
    'Attr9': 'Sales_to_Total_Assets',
    'Attr10': 'Equity_to_Total_Assets',
    'Attr11': 'Profit_to_Total_Assets',
    'Attr12': 'Gross_Profit_to_Short_Term_Liabilities',
    'Attr13': 'Gross_Profit_Plus_Depreciation_to_Sales',
    'Attr14': 'Gross_Profit_Plus_Interest_to_Total_Assets',
    'Attr15': 'Liabilities_to_Gross_Profit_Plus_Depreciation',
    'Attr16': 'Gross_Profit_Plus_Depreciation_to_Total_Liabilities',
    'Attr17': 'Total_Assets_to_Total_Liabilities',
    'Attr18': 'Gross_Profit_to_Total_Assets',
    'Attr19': 'Gross_Profit_to_Sales',
    'Attr20': 'Inventory_Turnover',
    'Attr21': 'Sales_Growth',
    'Attr22': 'Operating_Profit_to_Total_Assets',
    'Attr23': 'Net_Profit_to_Sales',
    'Attr24': 'Gross_Profit_3Y_to_Total_Assets',
    'Attr25': 'Adjusted_Equity_to_Total_Assets',
    'Attr26': 'Net_Profit_Plus_Depreciation_to_Total_Liabilities',
    'Attr27': 'Operating_Profit_to_Financial_Expenses',
    'Attr28': 'Working_Capital_to_Fixed_Assets',
    'Attr29': 'Log_Total_Assets',
    'Attr30': 'Adjusted_Liabilities_to_Sales',
    'Attr31': 'Gross_Profit_Plus_Interest_to_Sales',
    'Attr32': 'Current_Liabilities_to_Cost_of_Sales',
    'Attr33': 'Operating_Expenses_to_Short_Term_Liabilities',
    'Attr34': 'Operating_Expenses_to_Total_Liabilities',
    'Attr35': 'Profit_on_Sales_to_Total_Assets',
    'Attr36': 'Total_Sales_to_Total_Assets',
    'Attr37': 'Quick_Assets_to_Long_Term_Liabilities',
    'Attr38': 'Constant_Capital_to_Total_Assets',
    'Attr39': 'Profit_on_Sales_to_Sales',
    'Attr40': 'Net_Working_Capital_Ratio',
    'Attr41': 'Liabilities_to_Operating_Profit_Plus_Depreciation',
    'Attr42': 'Operating_Profit_to_Sales',
    'Attr43': 'Receivables_Plus_Inventory_Turnover',
    'Attr44': 'Receivables_Turnover',
    'Attr45': 'Net_Profit_to_Inventory',
    'Attr46': 'Net_Quick_Assets_to_Short_Term_Liabilities',
    'Attr47': 'Inventory_Turnover_COGS',
    'Attr48': 'EBITDA_to_Total_Assets',
    'Attr49': 'EBITDA_to_Sales',
    'Attr50': 'Current_Assets_to_Total_Liabilities',
    'Attr51': 'Short_Term_Liabilities_to_Total_Assets',
    'Attr52': 'Short_Term_Liabilities_to_COGS',
    'Attr53': 'Equity_to_Fixed_Assets',
    'Attr54': 'Constant_Capital_to_Fixed_Assets',
    'Attr55': 'Working_Capital',
    'Attr56': 'Gross_Margin',
    'Attr57': 'Net_Quick_Assets_to_Adjusted_Sales',
    'Attr58': 'Total_Costs_to_Total_Sales',
    'Attr59': 'Long_Term_Liabilities_to_Equity',
    'Attr60': 'Inventory_Turnover_Sales',
    'Attr61': 'Receivables_Turnover_Sales',
    'Attr62': 'Short_Term_Liabilities_Turnover',
    'Attr63': 'Sales_to_Short_Term_Liabilities',
    'Attr64': 'Sales_to_Fixed_Assets'
}


# Rename the columns
df6.rename(columns=column_name_mapping, inplace=True)

In [6]:
df6.head()

Net_Profit_to_Total_Assets  Total_Liabilities_to_Total_Assets  \
0                    0.200550                            0.37951   
1                    0.209120                            0.49988   
2                    0.248660                            0.69592   
3                    0.081483                            0.30734   
4                    0.187320                            0.61323   

   Working_Capital_to_Total_Assets  Current_Assets_to_Short_Term_Liabilities  \
0                          0.39641                                    2.0472   
1                          0.47225                                    1.9447   
2                          0.26713                                    1.5548   
3                          0.45879                                    2.4928   
4                          0.22960                                    1.4063   

   Liquidity_Ratio  Retained_Earnings_to_Total_Assets  EBIT_to_Total_Assets  \
0          32.3510                            0.38825              0.249760   
1          14.7860                            0.00000              0.258340   
2          -1.1523                            0.00000              0.309060   
3          51.9520                            0.14988              0.092704   
4          -7.3128                            0.18732              0.187320   

   Book_Value_of_Equity_to_Total_Liabilities  Sales_to_Total_Assets  \
0                                    1.33050                 1.1389   
1                                    0.99601                 1.6996   
2                                    0.43695                 1.3090   
3                                    1.86610                 1.0571   
4                                    0.63070                 1.1559   

   Equity_to_Total_Assets  ...  Gross_Margin  \
0                 0.50494  ...      0.121960   
1                 0.49788  ...      0.121300   
2                 0.30408  ...      0.241140   
3                 0.57353  ...      0.054015   
4                 0.38677  ...      0.134850   

   Net_Quick_Assets_to_Adjusted_Sales  Total_Costs_to_Total_Sales  \
0                             0.39718                     0.87804   
1                             0.42002                     0.85300   
2                             0.81774                     0.76599   
3                             0.14207                     0.94598   
4                             0.48431                     0.86515   

   Long_Term_Liabilities_to_Equity  Inventory_Turnover_Sales  \
0                         0.001924                    8.4160   
1                         0.000000                    4.1486   
2                         0.694840                    4.9909   
3                         0.000000                    4.5746   
4                         0.124440                    6.3985   

   Receivables_Turnover_Sales  Short_Term_Liabilities_Turnover  \
0                      5.1372                           82.658   
1                      3.2732                          107.350   
2                      3.9510                          134.270   
3                      3.6147                           86.435   
4                      4.3158                          127.210   

   Sales_to_Short_Term_Liabilities  Sales_to_Fixed_Assets  class  
0                           4.4158                 7.4277      0  
1                           3.4000                60.9870      0  
2                           2.7185                 5.2078      0  
3                           4.2228                 5.5497      0  
4                           2.8692                 7.8980      0  

[5 rows x 65 columns]

In [7]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None) 
pd.set_option('display.max_colwidth', None)

In [8]:
df6.isnull().sum()

Net_Profit_to_Total_Assets                                 8
Total_Liabilities_to_Total_Assets                          8
Working_Capital_to_Total_Assets                            8
Current_Assets_to_Short_Term_Liabilities                 134
Liquidity_Ratio                                           89
Retained_Earnings_to_Total_Assets                          8
EBIT_to_Total_Assets                                       8
Book_Value_of_Equity_to_Total_Liabilities                 94
Sales_to_Total_Assets                                      9
Equity_to_Total_Assets                                     8
Profit_to_Total_Assets                                    44
Gross_Profit_to_Short_Term_Liabilities                   134
Gross_Profit_Plus_Depreciation_to_Sales                  127
Gross_Profit_Plus_Interest_to_Total_Assets                 8
Liabilities_to_Gross_Profit_Plus_Depreciation             36
Gross_Profit_Plus_Depreciation_to_Total_Liabilities       95
Total_Assets_to_Total_Li

In [9]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43405 entries, 0 to 5909
Data columns (total 65 columns):
 #   Column                                               Non-Null Count  Dtype  
---  ------                                               --------------  -----  
 0   Net_Profit_to_Total_Assets                           43397 non-null  float64
 1   Total_Liabilities_to_Total_Assets                    43397 non-null  float64
 2   Working_Capital_to_Total_Assets                      43397 non-null  float64
 3   Current_Assets_to_Short_Term_Liabilities             43271 non-null  float64
 4   Liquidity_Ratio                                      43316 non-null  float64
 5   Retained_Earnings_to_Total_Assets                    43397 non-null  float64
 6   EBIT_to_Total_Assets                                 43397 non-null  float64
 7   Book_Value_of_Equity_to_Total_Liabilities            43311 non-null  float64
 8   Sales_to_Total_Assets                                43396 non-null  flo

In [10]:
df6['class'].unique()

array([0, 1])

In [11]:
df6['class'].value_counts()

class
0    41314
1     2091
Name: count, dtype: int64

In [12]:
for col in df6.columns:
    df6[col] = df6[col].astype(float)

In [13]:
df6.replace('?', np.nan, inplace=True)
for col in df6.columns:
    df6[col] = df6[col].astype(float)

In [14]:
df6.info()

<class 'pandas.core.frame.DataFrame'>
Index: 43405 entries, 0 to 5909
Data columns (total 65 columns):
 #   Column                                               Non-Null Count  Dtype  
---  ------                                               --------------  -----  
 0   Net_Profit_to_Total_Assets                           43397 non-null  float64
 1   Total_Liabilities_to_Total_Assets                    43397 non-null  float64
 2   Working_Capital_to_Total_Assets                      43397 non-null  float64
 3   Current_Assets_to_Short_Term_Liabilities             43271 non-null  float64
 4   Liquidity_Ratio                                      43316 non-null  float64
 5   Retained_Earnings_to_Total_Assets                    43397 non-null  float64
 6   EBIT_to_Total_Assets                                 43397 non-null  float64
 7   Book_Value_of_Equity_to_Total_Liabilities            43311 non-null  float64
 8   Sales_to_Total_Assets                                43396 non-null  flo

In [15]:
df6['class'] = df6['class'].astype(int)

In [16]:
data = df6.copy()

In [17]:
data.head()

Net_Profit_to_Total_Assets  Total_Liabilities_to_Total_Assets  \
0                    0.200550                            0.37951   
1                    0.209120                            0.49988   
2                    0.248660                            0.69592   
3                    0.081483                            0.30734   
4                    0.187320                            0.61323   

   Working_Capital_to_Total_Assets  Current_Assets_to_Short_Term_Liabilities  \
0                          0.39641                                    2.0472   
1                          0.47225                                    1.9447   
2                          0.26713                                    1.5548   
3                          0.45879                                    2.4928   
4                          0.22960                                    1.4063   

   Liquidity_Ratio  Retained_Earnings_to_Total_Assets  EBIT_to_Total_Assets  \
0          32.3510                            0.38825              0.249760   
1          14.7860                            0.00000              0.258340   
2          -1.1523                            0.00000              0.309060   
3          51.9520                            0.14988              0.092704   
4          -7.3128                            0.18732              0.187320   

   Book_Value_of_Equity_to_Total_Liabilities  Sales_to_Total_Assets  \
0                                    1.33050                 1.1389   
1                                    0.99601                 1.6996   
2                                    0.43695                 1.3090   
3                                    1.86610                 1.0571   
4                                    0.63070                 1.1559   

   Equity_to_Total_Assets  Profit_to_Total_Assets  \
0                 0.50494                0.249760   
1                 0.49788                0.261140   
2                 0.30408                0.312580   
3                 0.57353                0.092704   
4                 0.38677                0.187320   

   Gross_Profit_to_Short_Term_Liabilities  \
0                                 0.65980   
1                                 0.51680   
2                                 0.64184   
3                                 0.30163   
4                                 0.33147   

   Gross_Profit_Plus_Depreciation_to_Sales  \
0                                 0.166600   
1                                 0.158350   
2                                 0.244350   
3                                 0.094257   
4                                 0.121820   

   Gross_Profit_Plus_Interest_to_Total_Assets  \
0                                    0.249760   
1                                    0.258340   
2                                    0.309060   
3                                    0.092704   
4                                    0.187320   

   Liabilities_to_Gross_Profit_Plus_Depreciation  \
0                                         497.42   
1                                         677.96   
2                                         794.16   
3                                         917.01   
4                                        1133.20   

   Gross_Profit_Plus_Depreciation_to_Total_Liabilities  \
0                                              0.73378   
1                                              0.53838   
2                                              0.45961   
3                                              0.39803   
4                                              0.32211   

   Total_Assets_to_Total_Liabilities  Gross_Profit_to_Total_Assets  \
0                             2.6349                      0.249760   
1                             2.0005                      0.258340   
2                             1.4369                      0.309060   
3                             3.2537                      0.092704   
4                             1.6307 

In [18]:
df = data.sample(n=1000,random_state=100).reset_index(drop=True)

In [19]:
df.shape

(1000, 65)

In [21]:
df.shape

(1000, 65)

In [22]:
df['class'].value_counts()

class
0    957
1     43
Name: count, dtype: int64

In [23]:
plt.rcParams['figure.figsize'] = [80,120]
fig,ax = plt.subplots(20,4)
for c, a in zip(df.columns,ax.flatten()):
    sns.boxplot(df[c],ax=a,orient='h')
    plt.xlabel(c)
plt.tight_layout()
plt.show()

In [25]:
data.isnull().sum()

Net_Profit_to_Total_Assets                                 8
Total_Liabilities_to_Total_Assets                          8
Working_Capital_to_Total_Assets                            8
Current_Assets_to_Short_Term_Liabilities                 134
Liquidity_Ratio                                           89
Retained_Earnings_to_Total_Assets                          8
EBIT_to_Total_Assets                                       8
Book_Value_of_Equity_to_Total_Liabilities                 94
Sales_to_Total_Assets                                      9
Equity_to_Total_Assets                                     8
Profit_to_Total_Assets                                    44
Gross_Profit_to_Short_Term_Liabilities                   134
Gross_Profit_Plus_Depreciation_to_Sales                  127
Gross_Profit_Plus_Interest_to_Total_Assets                 8
Liabilities_to_Gross_Profit_Plus_Depreciation             36
Gross_Profit_Plus_Depreciation_to_Total_Liabilities       95
Total_Assets_to_Total_Li

In [26]:
data = data.apply(lambda x: x.fillna(x.median()), axis=0)

In [27]:
data.isnull().sum()

Net_Profit_to_Total_Assets                             0
Total_Liabilities_to_Total_Assets                      0
Working_Capital_to_Total_Assets                        0
Current_Assets_to_Short_Term_Liabilities               0
Liquidity_Ratio                                        0
Retained_Earnings_to_Total_Assets                      0
EBIT_to_Total_Assets                                   0
Book_Value_of_Equity_to_Total_Liabilities              0
Sales_to_Total_Assets                                  0
Equity_to_Total_Assets                                 0
Profit_to_Total_Assets                                 0
Gross_Profit_to_Short_Term_Liabilities                 0
Gross_Profit_Plus_Depreciation_to_Sales                0
Gross_Profit_Plus_Interest_to_Total_Assets             0
Liabilities_to_Gross_Profit_Plus_Depreciation          0
Gross_Profit_Plus_Depreciation_to_Total_Liabilities    0
Total_Assets_to_Total_Liabilities                      0
Gross_Profit_to_Total_Assets   

In [29]:
x = data.drop('class',axis=1)
y = data['class']

#### Data Scaling

In [30]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
scale = x.copy()
scaled = sc.fit_transform(scale)
scaled_df = pd.DataFrame(scaled,columns=x.columns)

In [31]:
scaled_df.head()

Net_Profit_to_Total_Assets  Total_Liabilities_to_Total_Assets  \
0                    0.055243                          -0.036062   
1                    0.058106                          -0.015458   
2                    0.071313                           0.018098   
3                    0.015472                          -0.048415   
4                    0.050824                           0.003944   

   Working_Capital_to_Total_Assets  Current_Assets_to_Short_Term_Liabilities  \
0                         0.051842                                 -0.014418   
1                         0.065787                                 -0.014765   
2                         0.028073                                 -0.016087   
3                         0.063312                                 -0.012907   
4                         0.021172                                 -0.016590   

   Liquidity_Ratio  Retained_Earnings_to_Total_Assets  EBIT_to_Total_Assets  \
0         0.006815                           0.061710              0.027359   
1         0.006527                           0.007791              0.028861   
2         0.006267                           0.007791              0.037740   
3         0.007135                           0.028606             -0.000134   
4         0.006166                           0.033805              0.016429   

   Book_Value_of_Equity_to_Total_Liabilities  Sales_to_Total_Assets  \
0                                  -0.022332              -0.024044   
1                                  -0.022994              -0.015133   
2                                  -0.024100              -0.021341   
3                                  -0.021272              -0.025344   
4                                  -0.023717              -0.023774   

   Equity_to_Total_Assets  Profit_to_Total_Assets  \
0               -0.008310                0.022387   
1               -0.008792                0.024533   
2               -0.022003                0.034231   
3               -0.003635               -0.007224   
4               -0.016366                0.010615   

   Gross_Profit_to_Short_Term_Liabilities  \
0                               -0.006960   
1                               -0.009079   
2                               -0.007226   
3                               -0.012267   
4                               -0.011825   

   Gross_Profit_Plus_Depreciation_to_Sales  \
0                                -0.007381   
1                                -0.007476   
2                                -0.006485   
3                                -0.008214   
4                                -0.007897   

   Gross_Profit_Plus_Interest_to_Total_Assets  \
0                                    0.027357   
1                                    0.028859   
2                                    0.037738   
3                                   -0.000136   
4                                    0.016427   

   Liabilities_to_Gross_Profit_Plus_Depreciation  \
0                                      -0.015494   
1                                      -0.013621   
2                                      -0.012416   
3                                      -0.011141   
4                                      -0.008899   

   Gross_Profit_Plus_Depreciation_to_Total_Liabilities  \
0                                            -0.009860   
1                                            -0.012715   
2                                            -0.013865   
3                                            -0.014765   
4                                            -0.015874   

   Total_Assets_to_Total_Liabilities  Gross_Profit_to_Total_Assets  \
0                          -0.021987                      0.026355   
1                          -0.023239                      0.027851   
2                          -0.024351                      0.036692   
3                          -0.020766                     -0.001020   
4                          -0.023969 

In [32]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(scaled_df,y,train_size=0.70,random_state=1000)

#### Random Forest 

In [33]:
from sklearn.ensemble import RandomForestClassifier
rfc = RandomForestClassifier()
rfc_model = rfc.fit(xtrain,ytrain)

In [34]:
test_pred = rfc_model.predict(xtest)
train_pred = rfc_model.predict(xtrain)

In [35]:
from sklearn.metrics import classification_report,confusion_matrix

In [36]:
print(classification_report(ytest,test_pred))

              precision    recall  f1-score   support

           0       0.96      1.00      0.98     12397
           1       0.80      0.24      0.37       625

    accuracy                           0.96     13022
   macro avg       0.88      0.62      0.67     13022
weighted avg       0.96      0.96      0.95     13022



In [37]:
print(classification_report(ytrain,train_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28917
           1       1.00      1.00      1.00      1466

    accuracy                           1.00     30383
   macro avg       1.00      1.00      1.00     30383
weighted avg       1.00      1.00      1.00     30383



In [38]:
confusion_matrix(ytest,test_pred)

array([[12359,    38],
       [  475,   150]])

In [39]:
confusion_matrix(ytrain,train_pred)

array([[28917,     0],
       [    0,  1466]])

#### XGBoost

In [45]:
pip install xgboost

  Obtaining dependency information for xgboost from https://files.pythonhosted.org/packages/0e/57/900d6efd517aea09de07a22f26ec3bb757f744b96d098a24aa383d47cfb9/xgboost-2.1.2-py3-none-macosx_12_0_arm64.whl.metadata
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.9/1.9 MB 2.9 MB/s eta 0:00:0000:0100:01
Note: you may need to restart the kernel to use updated packages.


In [46]:
from xgboost import XGBClassifier
xgb = XGBClassifier()
xgb_model = xgb.fit(xtrain,ytrain)

In [47]:
xgb_test = xgb_model.predict(xtest)
xgb_train = xgb_model.predict(xtrain)

In [48]:
print(classification_report(ytest,xgb_test))

              precision    recall  f1-score   support

           0       0.98      1.00      0.99     12397
           1       0.90      0.55      0.68       625

    accuracy                           0.98     13022
   macro avg       0.94      0.77      0.83     13022
weighted avg       0.97      0.98      0.97     13022



In [49]:
print(classification_report(ytrain,xgb_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28917
           1       1.00      0.99      1.00      1466

    accuracy                           1.00     30383
   macro avg       1.00      1.00      1.00     30383
weighted avg       1.00      1.00      1.00     30383



In [50]:
confusion_matrix(ytest,xgb_test)

array([[12361,    36],
       [  283,   342]])

In [51]:
confusion_matrix(ytrain,xgb_train)

array([[28916,     1],
       [   13,  1453]])

#### PCA Model

In [52]:
from sklearn.decomposition import PCA
pca = PCA(0.80)
pca_model = pca.fit_transform(scaled_df)

In [53]:
pca_model.shape

(43405, 17)

In [54]:
pca_df = pd.DataFrame(pca_model,columns=['pc1','pc2','pc3','pc4','pc5','pc6','pc7','pc8','pc9','pc10','pc11','pc12','pc13','pc14','pc15','pc16','pc17'])

In [55]:
pca_df.head()

pc1       pc2       pc3       pc4       pc5       pc6       pc7  \
0 -0.016269 -0.027210 -0.083602 -0.003692 -0.343796  0.003315 -0.029898   
1  0.024316 -0.015597 -0.036650 -0.050978 -0.042707  0.002006 -0.052397   
2  0.019456 -0.016326 -0.009394 -0.081417 -0.125816  0.002965 -0.061419   
3 -0.057996 -0.021281 -0.081724 -0.011272 -0.150529 -0.002928 -0.022868   
4 -0.020501 -0.017992 -0.023032 -0.065526 -0.091935 -0.000297 -0.046418   

        pc8       pc9      pc10      pc11      pc12      pc13      pc14  \
0  0.210852 -0.048897 -0.138474  0.028081  0.462741  4.948173  0.006486   
1  0.045133 -0.008170 -0.014788 -0.008895 -0.066248 -0.317570 -0.028355   
2  0.066586 -0.016151 -0.077747  0.004309 -0.012659  0.281601 -0.021702   
3  0.051480 -0.021040 -0.040252 -0.000687  0.056979  0.642314 -0.009061   
4  0.040015 -0.014344 -0.060083  0.000317 -0.023875  0.062266 -0.019760   

       pc15      pc16      pc17  
0  0.107923 -0.112618 -0.149862  
1 -0.016739 -0.035391  0.003385  
2 -0.012525  0.041220 -0.003062  
3 -0.004533  0.044115 -0.000783  
4 -0.011296  0.032937 -0.010288

#### PCA Radnom Forest

In [56]:
xtrain,xtest,ytrain,ytest = train_test_split(pca_df,y,test_size=0.30,random_state=1000)

In [57]:
rfc = RandomForestClassifier()
rfc_model = rfc.fit(xtrain,ytrain)

In [58]:
rfc_test = rfc_model.predict(xtest)
rfc_train = rfc_model.predict(xtrain)

In [59]:
print(classification_report(ytest,rfc_test))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97     12397
           1       0.08      0.01      0.02       625

    accuracy                           0.95     13022
   macro avg       0.52      0.50      0.49     13022
weighted avg       0.91      0.95      0.93     13022



In [60]:
print(classification_report(ytrain,rfc_train))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00     28917
           1       1.00      1.00      1.00      1466

    accuracy                           1.00     30383
   macro avg       1.00      1.00      1.00     30383
weighted avg       1.00      1.00      1.00     30383



In [61]:
confusion_matrix(ytest,rfc_test)

array([[12326,    71],
       [  619,     6]])

#### PCA XGBoost

In [62]:
xgb = XGBClassifier()
xgb_model =xgb.fit(xtrain,ytrain)

In [63]:
xgb_test = xgb_model.predict(xtest)
xgb_train = xgb_model.predict(xtrain)

In [64]:
print(classification_report(ytest,xgb_test))

              precision    recall  f1-score   support

           0       0.95      0.99      0.97     12397
           1       0.07      0.01      0.01       625

    accuracy                           0.95     13022
   macro avg       0.51      0.50      0.49     13022
weighted avg       0.91      0.95      0.93     13022



In [65]:
print(classification_report(ytrain,xgb_train))

              precision    recall  f1-score   support

           0       0.97      1.00      0.99     28917
           1       1.00      0.48      0.65      1466

    accuracy                           0.97     30383
   macro avg       0.99      0.74      0.82     30383
weighted avg       0.98      0.97      0.97     30383



In [66]:
confusion_matrix(ytest,xgb_test)

array([[12334,    63],
       [  620,     5]])

In [67]:
confusion_matrix(ytrain,xgb_train)

array([[28916,     1],
       [  763,   703]])